//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace КП1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log_in
    {
        public string Login { get; set; }
        public byte[] Password { get; set; }
        public int ID { get; set; }
    
        public virtual User User { get; set; }
    }
}
