//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace КП1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Friend
    {
        public int Id { get; set; }
        public int MyID { get; set; }
        public int FriendID { get; set; }
        public string Name { get; set; }
        public string LName { get; set; }
        public byte[] Photo { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
